### ISSUE TITLE
Store tests seem to check wrong address

### ISSUE THREAD

**Issue by jerryz123** [ksco/riscv-vector-tests#11]
After performing the store, a load is performed from `resultdata`, while the store stores to `testdata`. Not sure what the intent is, but the current behavior doesn't actually check the result of the stores.

**Comment by ksco** [comment]
Hmmm, I'll take a look tomorrow. Thanks!

**Comment by ksco** [comment]
Fixed above. The `la a0, resultdata` is put into the wrong place: 

```diff
# Move a0 to test data area.
la a0, testdata
li a5, 160
add a0, a0, a5

# Load data into v1 register group.
li t0, -1
vsetvli t1, t0, e8,m1,ta,ma
vle8.v v1, (a0)

+ la a0, resultdata
# -------------- TEST BEGIN --------------
li t0, 32
vsetvli t1, t0, e8,mf8,ta,ma
vse8.v v1, (a0)
# -------------- TEST END   --------------
- la a0, resultdata

# Load data into v1 register group.
li t0, -1
vsetvli t1, t0, e8,m1,ta,ma
vle8.v v1, (a0)
```

**Comment by jerryz123** [comment]
Thanks!

**Comment by jerryz123** [comment]
This might affect all the store types though, including strided and indexed.

**Comment by ksco** [comment]
I believe I've got them all.

**Comment by jerryz123** [comment]
Thanks!
