### ISSUE TITLE
Restrict virtual mode tests to vector load/store only?

### ISSUE THREAD

**Issue by jerryz123** [ksco/riscv-vector-tests#17]
Generating only the load/store cases for virtual-mode will reduce the number of generated binaries.

**Comment by ksco** [comment]
Sure, I'll add that option later this week.

**Comment by ksco** [comment]
Sorry for the delay, I missed this. I added a `PATTERN` option above, now one can use `make -j4 -e PATTERN='^v[ls].+\.v$'` to generate load/store tests only.
