### ISSUE TITLE
Test all cases of VXRM.

### ISSUE THREAD

**Issue by jerryz123** [ksco/riscv-vector-tests#19]
Currently only vxrm=0 is tested, I think

**Comment by ksco** [comment]
Added vxrm traversal for `vaadd*`, `vasub*`, `vnclip*`, `vsmul*`, `vssra*` and `vssrl*` instructions. I believe that's all the instructions that use vxrm.

**Comment by jerryz123** [comment]
Thanks! This is much appreciated
