### ISSUE TITLE
Use tail/mask undisturbed instead of agnostic

### ISSUE THREAD

**Issue by troibe** [ksco/riscv-vector-tests#35]
Currently the tests use tail and mask agnostic.
We then check the full vector registers for their values.
I think if we want to be implementation independent (especially for out-of-order cores),
we should use undisturbed for checking the full vector registers.

Alternatively we can only check the parts of the vector registers where the agnostic policy does not have an effect.

**Comment by ksco** [comment]
If the agnostic parts are not "undisturbed", then it is a complicated feature to implement, especially for the mask agnostic. I think it would be more proper to implement a co-simulator and then use `TEST_MODE=cosim` to generate tests instead of torturing tests writers :smile_cat:

**Comment by troibe** [comment]
Sure I understand that using agnostic perfectly would be a lot of manual work.
What do you think about using undisturbed mode by default then?

**Comment by ksco** [comment]
Ah yes, make the undisturbed default sounds reasonable, can you submit a PR addressing this? And even make it an option in the Makefile maybe.

**Comment by troibe** [comment]
Sure sounds good.

**Comment by ksco** [comment]
Nah, for now, I don't think it's worth an option, made a simple replacement above.

**Comment by troibe** [comment]
Sorry about leaving it open for that long.
I knew the changes were simple but wasn't sure about verifying their correctness.
Anyways thanks for closing the issue.
