### ISSUE TITLE
Custom tests generation

### ISSUE THREAD

**Issue by akifejaz** [ksco/riscv-vector-tests#36]
Hi!

I don't want to generate few tests, how can I add them, so they don't generate? or maybe how to skip some tests run on SPIKE? 

Best,
Akif

@ksco @jerryz123 @Avimitin

**Comment by ksco** [comment]
There is a `PATTERN` option for this, see: https://github.com/ksco/riscv-vector-tests?tab=readme-ov-file#how-to-use
