### ISSUE TITLE
Add tests for vlseg<nf>e<eew>ff.v

### ISSUE THREAD

**Issue by troibe** [ksco/riscv-vector-tests#39]
I might have missed it but I don't think we are covering those right now.

**Comment by ksco** [comment]
Ah yes, I don't even know these instructions exists, do they? Anyway, the issue is fault-on-first is, it's harder to writes, for now, we just tested them as normal memory loads, look at `vle8ff.v` for example.

**Comment by ksco** [comment]
Done
